name: saayer
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: "^3.2.5"
  flutter: "^3.16.8"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  firebase_storage: ^11.6.4
  firebase_messaging: ^14.7.14
  firebase_dynamic_links: ^5.4.12
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter_inappwebview: ^6.0.0
  lottie: ^3.0.0
  cached_network_image: ^3.3.1
  fast_cached_network_image: any
  connectivity_plus: any
  url_launcher: ^6.2.4
  webview_flutter_web: ^0.2.2+4
  device_info_plus: ^9.1.2
  package_info_plus: ^5.0.1
  easy_localization: ^3.0.3
  loader_overlay: ^4.0.0
  get_it: ^7.6.7
  injectable: ^2.3.2
  validators: ^3.0.0
  http_certificate_pinning: ^2.1.3
  fluttertoast: ^8.2.2
  flutter_countdown_timer: ^4.1.0
  flutter_svg: ^2.0.9
  intl: any
  flutter_secure_storage: ^9.0.0
  permission_handler: any
  permission_handler_web: any
  flutter_screenutil: ^5.9.0
  flutter_web_frame: ^1.0.0
  universal_html: ^2.2.4
  easy_localization_loader: ^2.0.1
  url_strategy: ^0.2.0
  flutter_localized_locales: ^2.0.5
  path_provider: ^2.1.2
  dartz: ^0.10.1
  cupertino_icons: ^1.0.6
  adaptive_theme: ^3.6.0
  internet_connection_checker: ^1.0.0+1
  google_fonts: ^6.1.0
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  animated_introduction: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.3
  intl_phone_number_input: ^0.7.4
  panara_dialogs: ^0.1.4
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  encrypt_decrypt_plus: ^1.1.0

#fvm flutter packages pub run build_runner build
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:
  build_runner:
  flutter_gen_runner:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  background_color: "#FFFFFF"
  image_path_ios: "assets/icons/ic_logo_with_bg.jpg"
  image_path_android: "assets/icons/ic_logo_with_bg.jpg"
  web:
    generate: true
    image_path: "assets/icons/ic_logo_with_bg.jpg"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/strings/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/gifs/
    - assets/files/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
