// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgyA_eCIGoUDK7gtOgE1A9v1l81Kq7mvo',
    appId: '1:522079680829:web:5956c632745cf37d7ead54',
    messagingSenderId: '522079680829',
    projectId: 'sayer-1dd9f',
    authDomain: 'sayer-1dd9f.firebaseapp.com',
    storageBucket: 'sayer-1dd9f.appspot.com',
    measurementId: 'G-5TBCJ2QLKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjg_4dVdLV_u1GrUa1IT_Qz52Iv-tv6-w',
    appId: '1:522079680829:android:ab2d26954dc4170f7ead54',
    messagingSenderId: '522079680829',
    projectId: 'sayer-1dd9f',
    storageBucket: 'sayer-1dd9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtxYUDV-skXoPox8SBNxTElJ4X2CNROpg',
    appId: '1:522079680829:ios:e7bac8c6aa26c0097ead54',
    messagingSenderId: '522079680829',
    projectId: 'sayer-1dd9f',
    storageBucket: 'sayer-1dd9f.appspot.com',
    iosBundleId: 'com.org.saayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtxYUDV-skXoPox8SBNxTElJ4X2CNROpg',
    appId: '1:522079680829:ios:a11d6aa70854117b7ead54',
    messagingSenderId: '522079680829',
    projectId: 'sayer-1dd9f',
    storageBucket: 'sayer-1dd9f.appspot.com',
    iosBundleId: 'com.org.saayer.RunnerTests',
  );
}
