import 'package:flutter/material.dart';

abstract class BaseColorsPalette {
  final Color primaryColor,
      accentColor,
      orangeColor,
      darkOrangeColor,
      superDarkOrangeColor,
      lightOrangeColor,
      blackTextColor,
      lightBlackTextColor,
      blueColor,
      greyColor,
      lightGreyColor,
      darkGreyColor,
      navBarColor,
      tabGreyColor,
      whiteColor,
      blackColor,
      greenColor,
      whiteAllOverColor,
      backgroundColor,
      transparent,
      error1,
      error0,
      neutral6,
      neutral5,
      neutral4,
      neutral3,
      neutral2,
      neutral1,
      neutral0,
      barrierColor,
      textFieldFillColor,
      lightYellowColor,
      lightGreenColor;

  const BaseColorsPalette(
      {required this.primaryColor,
      required this.accentColor,
      required this.orangeColor,
      required this.darkOrangeColor,
      required this.superDarkOrangeColor,
      required this.lightOrangeColor,
      required this.blackTextColor,
      required this.lightBlackTextColor,
      required this.blueColor,
      required this.greyColor,
      required this.lightGreyColor,
      required this.darkGreyColor,
      required this.navBarColor,
      required this.tabGreyColor,
      required this.whiteColor,
      required this.blackColor,
      required this.greenColor,
      required this.whiteAllOverColor,
      required this.backgroundColor,
      required this.transparent,
      required this.error1,
      required this.error0,
      required this.neutral6,
      required this.neutral5,
      required this.neutral4,
      required this.neutral3,
      required this.neutral2,
      required this.neutral1,
      required this.neutral0,
      required this.barrierColor,
      required this.textFieldFillColor,
      required this.lightYellowColor,
      required this.lightGreenColor});
}
